language: generic
sudo: false
deploy:
    -   provider: releases
        key:
            secure: "DQhD0qFgvkr9BTyac/Ql7YPW2OIjKchlt0e6Y9EEqD7LxtxKHiHXftUYGZ9LyAg7+6CNsLRnLBCMvnLjcgoMm6k4k7Bj6G9HUsVszLkRDNCo05rI7DuhZ7hUwSWAZirSUmNQ7qhe3KUL4E4PHJHl6hMt2bHyqZVQtpNptNtPAQkUyyOdJd+F+MjjL6l0gvI6BhIHgNcjnGFWpyMH+HglRqFcNqLHtQV4weYJXbBgh9LzliTXbhc1BljTtqX2+ZgVqEII03wRGsrlaf3uniwZvdGHD5Y4JNlCyiURfr//+YPQG3ZNIpZ1nCmsUxmylz2kGyty7ASzvr9lSkJJzZeQqjP/oL9q/hu9odIO1CfFy9yD+9cL0ntOSrxGKTwe6Nj7NrbPNqfdKSh5eIlz6/lqsFrXU+T0oIGY7xZQ45UpDCZkvibrljv93PUFIEWnP/lsuX0fikiDiPVv0aI6SHPrjUVh8WJqoGZ32WedpW9Pc4b9hYXaJWf4WhWuvFMwP7oDUue9ddc+6wvb9b0aFOKx/eItHCB37tZCTEiAq3jhTTbZTjAbrD98GDlzRZTx/R0yCUDu1DrxmRS/pghPfox3gEDuuSb3PYPRqc5CSwI0aur8srVcb8fiWT1Jp26qv2z4/wwBkJ6ILduqJc6tlI77YZrCGHJgoHp+gudsub3S+t4="
        file_glob: true
        file: /tmp/packages/*
        skip_cleanup: true
        on:
            tags: true

before_install:
  - |
        declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

        # Decrypt the file containing the private key
        openssl aes-256-cbc \
          -K $encrypted_bb0bdcea090b_key -iv $encrypted_bb0bdcea090b_iv \
          -in ".travis/github_deploy_key.enc" \
          -out "$SSH_FILE" -d

        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

        # Enable SSH authentication
        chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host github.com" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" >> ~/.ssh/config
              
        git config --global user.email "travis@travis-ci.org"
        git config --global user.name "Travis CI"
script:
    - ./ci/script.sh
before_deploy:
    - ./ci/before_deploy.sh